version: '2'

services:
  exchange_db:
    image: postgres
#    restart: always
    
    # mount ./init_sql, which contains .sql files used to create DB
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
    
    expose:
      - "5432"
    ports:
      - "54321:5432"
    
  server:
    build: ./exchange_server
    command: bash -c "make all && ./server"
    volumes:
      - ./exchange_server:/code
    expose:
      - "12345"
    ports:
      - "12345:12345"
    depends_on:
      - exchange_db
